use containerdb;



/*    NOTICE: TESTIMONIALS WILL BE APPROVED BY STATING THE WANTED "TESTIMONIALID       "*/



UPDATE tbl_testimonial SET APPROVED = 1 WHERE TESTIMONIALID = 1;
UPDATE tbl_testimonial SET APPROVED = 1 WHERE TESTIMONIALID = 2;
UPDATE tbl_testimonial SET APPROVED = 1 WHERE TESTIMONIALID = 3;
UPDATE tbl_testimonial SET APPROVED = 1 WHERE TESTIMONIALID = 4;
UPDATE tbl_testimonial SET APPROVED = 1 WHERE TESTIMONIALID = 5;
UPDATE tbl_testimonial SET APPROVED = 1 WHERE TESTIMONIALID = 6;
UPDATE tbl_testimonial SET APPROVED = 1 WHERE TESTIMONIALID = 7;