use containerdb;



/*    NOTICE: TESTIMONIALS WILL BE APPROVED BY STATING THE WANTED "TESTIMONIALID       "*/



UPDATE tbl_testimonial SET APPROVED = 1 WHERE TESTIMONIALID = 2;  /* Approval by TESTIMONIALID number */
